PastorHub/PastorNub/Controllers/CommonController.cs
using Microsoft.AspNet.Identity;
using PastorNub.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace PastorNub.Controllers
{
    public class CommonController : Controller
    {
        private static string SearchText = "";
        private static bool OnlyFavorite = false;

        public ActionResult Search(string Id = "", string Text = "")
        {
            ApplicationDbContext Context = new ApplicationDbContext();
            ApplicationUser CurrentUser = Context.Users.Find(User.Identity.GetUserId());

            List<Post> PostList = new List<Post>();

            if (OnlyFavorite)
            {
                foreach (Favorite i in Context.Favorites.Where(i => i.User.Id == CurrentUser.Id).OrderByDescending(i => i.Post.Date).ToList())
                {
                    PostList.Add(i.Post);
                }
            }
            else
            {
                PostList = Context.Posts.Where(i => Id == "" ? true : i.Autor.Id == Id).OrderByDescending(i => i.Date).ToList();
            }

            SearchText = Text;
            if (SearchText != "")
            {
                PostList = PostList.Where(i => i.Title.Contains(SearchText) || i.Text.Contains(SearchText) || i.Autor.UserName.Contains(SearchText)).ToList();
            }
            if (CurrentUser != null)
            {
                PostList = PostList.Where(i => i.Global == true ? true : (CurrentUser.Confession == null ? true : i.Confession.ConfessionName == CurrentUser.Confession.ConfessionName)).ToList();
            }

            return PartialView("PostList", PostList);
        }

        public ActionResult PostList(string Id = "", string SortBy = "", bool? Ascending = true, bool? Favorite = null)
        {
            if (Favorite != null)
            {
                OnlyFavorite = Favorite.Value;
            }

            ApplicationDbContext Context = new ApplicationDbContext();
            ApplicationUser CurrentUser = Context.Users.Find(User.Identity.GetUserId());

            List<Post> PostList = new List<Post>();

            if (OnlyFavorite)
            {
                foreach (Favorite i in Context.Favorites.Where(i => i.User.Id == CurrentUser.Id).OrderByDescending(i => i.Post.Date).ToList())
                {
                    PostList.Add(i.Post);
                }
            }
            else
            {
                PostList = Context.Posts.OrderByDescending(i => i.Date).ToList();
            }

            if (SearchText != "")
            {
                PostList = PostList.Where(i => i.Title.Contains(SearchText) || i.Text.Contains(SearchText) || i.Autor.UserName.Contains(SearchText)).ToList();
            }
            PostList = PostList.Where(i => Id == "" ? true : (i.Autor.Id == Id)).ToList();
            if (CurrentUser != null)
            {
                PostList = PostList.Where(i => i.Global == true ? true : (CurrentUser.Confession == null ? true : i.Confession.ConfessionName == CurrentUser.Confession.ConfessionName)).ToList();
            }

            if (SortBy != string.Empty)
            {
                if (Ascending.Value)
                {
                    switch (SortBy)
                    {
                        case "Name":
                            PostList = PostList.OrderBy(i => i.Title).ToList();
                            return PartialView(PostList);
                        case "Date":
                            PostList = PostList.OrderBy(i => i.Date).ToList();
                            return PartialView(PostList);
                        case "Fav":
                            PostList = PostList.OrderBy(i => i.Favorites.Count).ToList();
                            return PartialView(PostList);
                    }
                }
                else
                {
                    switch (SortBy)
                    {
                        case "Name":
                            PostList = PostList.OrderByDescending(i => i.Title).ToList();
                            return PartialView(PostList);
                        case "Date":
                            PostList = PostList.OrderByDescending(i => i.Date).ToList();
                            return PartialView(PostList);
                        case "Fav":
                            PostList = PostList.OrderByDescending(i => i.Favorites.Count).ToList();
                            return PartialView(PostList);
                    }
                }
            }

            return PartialView(PostList);
        }

        [HttpGet]
        public ActionResult EditComment(int Id)
        {
            ApplicationDbContext Context = new ApplicationDbContext();
            Comments CommentForEdit = Context.Comments.Find(Id);
            CommentForEdit.Text = CommentForEdit.Text.Replace("<br/>", "\r\n");
            return PartialView(CommentForEdit);
        }

        [HttpPost]
        public ActionResult EditComment(int Id, string Text)
        {
            if (string.IsNullOrEmpty(Text))
            {
                ModelState.AddModelError("Text", "Не введено текст коментаря");
            }
            ApplicationDbContext Context = new ApplicationDbContext();
            Comments CommentForEdit = Context.Comments.Find(Id);
            if (ModelState.IsValid)
            {   
                CommentForEdit.Text = Text.Replace("\r\n", "<br/>");
                Context.SaveChanges();
            }
            return PartialView(CommentForEdit);
        }

        public ActionResult DeleteConfirm(int Id)
        {
            ApplicationDbContext Context = new ApplicationDbContext();
            Comments CommentForDelete = Context.Comments.Find(Id);
            CommentForDelete.Text = CommentForDelete.Text.Replace("<br/>", "\r\n");
            return PartialView(CommentForDelete);
        }

        public ActionResult DeleteComment(int Id)
        {
            ApplicationDbContext Context = new ApplicationDbContext();
            Comments CommentForDelete = Context.Comments.Find(Id);
            Context.Comments.Remove(CommentForDelete);
            Context.SaveChanges();
            return null;
        }

        public ActionResult ShowExtended(int Id)
        {
            ApplicationDbContext Context = new ApplicationDbContext();
            Post PostForShow = Context.Posts.Find(Id);
            return PartialView(PostForShow);
        }

        public ActionResult ShowComments(int Id)
        {
            ApplicationDbContext Context = new ApplicationDbContext();
            return PartialView(Context.Posts.Find(Id));
        }

        public ActionResult Like(int Id)
        {
            ApplicationDbContext Context = new ApplicationDbContext();
            ApplicationUser CurrentUser = Context.Users.Find(User.Identity.GetUserId());
            Post TargetPost = Context.Posts.Find(Id);

            //Checking if user doesn't have this post in favorites
            if (Context.Favorites.Where(i => i.User.Id == CurrentUser.Id && i.Post.Id == TargetPost.Id).Count() <= 0)
            {
                Favorite NewFavorite = new Favorite
                {
                    Post = TargetPost,
                    User = CurrentUser
                };

                CurrentUser.Favorites.Add(NewFavorite);
                TargetPost.Favorites.Add(NewFavorite);

                Context.Favorites.Add(NewFavorite);

                Context.SaveChanges();
            }
            return PartialView(TargetPost);
        }

        public ActionResult Dislike(int Id)
        {
            ApplicationDbContext Context = new ApplicationDbContext();
            ApplicationUser CurrentUser = Context.Users.Find(User.Identity.GetUserId());
            Post TargetPost = Context.Posts.Find(Id);

            //Checking if user have this post in favorites
            if (Context.Favorites.Where(i => i.User.Id == CurrentUser.Id && i.Post.Id == TargetPost.Id).Count() > 0)
            {
                Favorite DeletingFavorite = Context.Favorites.Where(i => i.User.Id == CurrentUser.Id && i.Post.Id == TargetPost.Id).FirstOrDefault();

                CurrentUser.Favorites.Remove(DeletingFavorite);
                TargetPost.Favorites.Remove(DeletingFavorite);

                Context.Favorites.Remove(DeletingFavorite);

                Context.SaveChanges();
            }
            return PartialView(TargetPost);
        }

        [HttpPost]
        public ActionResult Comment(int Id, string Text)
        {
            if(string.IsNullOrEmpty(Text))
            {
                ModelState.AddModelError("Text", "Не введено текст коментаря");
            }

            ApplicationDbContext Context = new ApplicationDbContext();
            ApplicationUser CurrentUser = Context.Users.Find(User.Identity.GetUserId());
            Post TargetPost = Context.Posts.Find(Id);

            if (ModelState.IsValid)
            {
                Comments NewComment = new Comments
                {
                    Autor = CurrentUser,
                    Date = DateTime.Now,
                    Text = Text.Replace("\r\n", "<br/>"),
                    Post = TargetPost
                };

                TargetPost.Comments.Add(NewComment);

                Context.Comments.Add(NewComment);

                Context.SaveChanges();
            }

            return PartialView(TargetPost.Comments);
        }

        [HttpGet]
        public ActionResult Comment(int Id)
        {
            ApplicationDbContext Context = new ApplicationDbContext();
            return PartialView(Context.Comments.Where(i => i.Post.Id == Id).ToList());
        }

        public ActionResult Favorite()
        {
            return View();
        }

        public ActionResult Menu()
        {
            return PartialView();
        }

        public ActionResult NavMenu()
        {
            return PartialView();
        }

PastorHub/PastorNub/Views/Shared/_Layout.cshtml
@using Microsoft.AspNet.Identity;

<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" />
    <link href="/Content/bootstrap.css" rel="stylesheet">
    @{
        string Theme = "Light";
        if (Request.Cookies.Get("Theme") != null)
        {
            Theme = Request.Cookies.Get("Theme").Value;
        }

    }
    <link href="@Url.Content("~/Content/" + Theme + "Theme.css")" rel="stylesheet" type="text/css" id="Theme" />
    <script src="https://kit.fontawesome.com/02224f7914.js" crossorigin="anonymous"></script>
    @Scripts.Render("~/bundles/modernizr")

    <style>

        .RecentePost {
            transition: 0.3s;
        }

            .RecentePost:hover {
                cursor: pointer;
                transform: scale(1.1);
            }

        .PostStyle:hover {
            cursor: pointer;
        }

        .PostFilePlace {
            display: flex;
            max-height: 250px;
        }

        .File {
            overflow: hidden;
            object-fit: cover;
            transition: 0.3s;
        }

            .File:hover {
                position: relative;
                cursor: pointer;
                transform: scale(1.05);
                z-index: 999;
            }

        .hover:hover {
            background-color: darkgray;
            cursor: pointer;
        }

        .hover-ch:hover {
            cursor: pointer;
        }

        .PopUp {
            display: none;
            width: 100%;
            height: 100%;
            background-color: rgba(0,0,0,0.5);
            position: fixed;
            top: 0;
            bottom: 0;
            left: 0;
            right: 0;
            z-index: 100;
            overflow-y: scroll;
        }

        .LikeBtn > img {
            overflow: hidden;
            transition: 0.2s;
        }

        .LikeBtn:hover {
            cursor: pointer;
            transform: scale(0.8);
        }

        .LikeBtn > img:hover {
            transform: scale(0.8);
        }

        .LikeBtn > img:active {
            transform: scale(1.3) !important;
        }

        .LikeBtn:active {
            transform: scale(1s) !important;
        }
    </style>

</head>
<body>
    <nav class="navbar navbar-expand navbar-dark bg-dark fixed-top">
        <a class="navbar-brand" href="~/Home/Index">PastorHub</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a href="~/Home/Index" class="nav-link">Домашня сторінка</a></li>
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="nav-item "> <a href="~/User/Subscriptions" class="nav-link">Підписки</a></li>
                    <li class="nav-item "> <a href="~/Profile/Index/@(User.Identity.GetUserId())" class="nav-link">Профіль</a></li>
                    if (User.IsInRole("pastor"))
                    {

                        <li class="nav-item "> <a href="~/Profile/PostManager" class="nav-link">Менеджер постів</a></li>
                    }
                    if (User.IsInRole("administrator"))
                    {
                        <li class="nav-item "> <a href="~/Administrator/ConfessionsManager" class="nav-link">Менеджер конфесій</a></li>
                    }
                    <li class="nav-item "> <a class="nav-link" href="/Common/Favorite/">Пости, які сподобалися</a></li>
                    <li class="nav-item "> <a href="~/Messages/Index" class="nav-link">Повідомлення</a></li>
                }
            </ul>
            @Html.Partial("_LoginPartial")
        </div>
    </nav>
    <div class="body-content">
        @RenderBody()
    </div>


    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/scripts/jquery-3.5.1.js")
    @Scripts.Render("~/scripts/jquery.unobtrusive-ajax.js")
    @RenderSection("scripts", required: false)


    <script>
    function RenderMenu(Id) {
        $("#menu").attr("class", "container-fluid position-absolute position-fixed row");
        $("#menu").load('@Url.Action("Menu", "Common")', function () {
            $("#NavigationMenu").load('@Url.Action("NavMenu", "Common")');
            $("#SortMenu").load('@Url.Action("SortMenu", "Common")?Id=' + Id);
            $("#MessagesMenu").load('@Url.Action("MessagesMenu", "Common")');
            $("#RecentMenu").load('@Url.Action("RecentMenu", "Common")');
        });
    }

    function get_cookie(cookie_name) {
        var results = document.cookie.match('(^|;) ?' + cookie_name + '=([^;]*)(;|$)');

        if (results)
            return (unescape(results[2]));
        else
            return null;
    }

    document.addEventListener('DOMContentLoaded', function () {

        if (get_cookie("Theme") == null) {
            document.cookie = "Theme=Light; path=/";
        }
        else if (get_cookie("Theme") == "Dark") {
             document.getElementById("Theme").setAttribute("href", "@Url.Content("~/Content/DarkTheme.css")");
        }
        else {
          document.getElementById("Theme").setAttribute("href", "@Url.Content("~/Content/LightTheme.css")");
        }
    });

    function Dark() {
        document.cookie = "Theme=Dark; path=/";
        document.getElementById("Theme").setAttribute("href", "@Url.Content("~/Content/DarkTheme.css")");
    }
    function Light() {
        document.cookie = "Theme=Light; path=/";
        document.getElementById("Theme").setAttribute("href", "@Url.Content("~/Content/LightTheme.css")");
    }
    </script>
</body>
</html>